### ISSUE TITLE
Invoking "make -j12 -l12" failed

### ISSUE THREAD

**Issue by Hossam-Elbahrawy** [sigmaai/self-driving-golf-cart#10]
Catkin_make doesn't work and everything falls apart when the process reaches cv_camera_node or that what I think.
Here is a log of the Error

`[ 80%] Building CXX object sensors/cv_camera/CMakeFiles/cv_camera_nodelet.dir/src/cv_camera_nodelet.cpp.o
[ 80%] Built target autopilot_generate_messages_cpp
[ 80%] Built target autopilot_generate_messages_py
[ 86%] Built target rosbridge_library_generate_messages_cpp
[ 93%] Built target rosbridge_library_generate_messages_py
[100%] Built target rosbridge_library_generate_messages_lisp
[100%] Built target autopilot_generate_messages_eus
[100%] Built target autopilot_generate_messages_lisp
[100%] Built target object_detection_generate_messages
[100%] Built target simulation_generate_messages
[100%] Built target segmentation_generate_messages
/usr/bin/ld: cannot find -luv
/usr/bin/ld: cannot find -luWS
[100%] Built target rosapi_generate_messages
[100%] Built target rosbridge_library_generate_messages
collect2: error: ld returned 1 exit status
localization/CMakeFiles/particle_filter.dir/build.make:139: recipe for target '/media/bazkleer/Fast_Stuff/Carla Stable/self-driving-golf-cart/ros/devel/lib/localization/particle_filter' failed
make[2]: *** [/media/bazkleer/Fast_Stuff/Carla Stable/self-driving-golf-cart/ros/devel/lib/localization/particle_filter] Error 1
CMakeFiles/Makefile2:8821: recipe for target 'localization/CMakeFiles/particle_filter.dir/all' failed
make[1]: *** [localization/CMakeFiles/particle_filter.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
[100%] Built target autopilot_generate_messages
/media/bazkleer/Fast_Stuff/Carla Stable/self-driving-golf-cart/ros/src/sensors/cv_camera/src/cv_camera_nodelet.cpp:80:24: error: expected constructor, destructor, or type conversion before ‘(’ token
 PLUGINLIB_DECLARE_CLASS(cv_camera, CvCameraNodelet, cv_camera::CvCameraNodelet, nodelet::Nodelet);
                        ^
sensors/cv_camera/CMakeFiles/cv_camera_nodelet.dir/build.make:62: recipe for target 'sensors/cv_camera/CMakeFiles/cv_camera_nodelet.dir/src/cv_camera_nodelet.cpp.o' failed
make[2]: *** [sensors/cv_camera/CMakeFiles/cv_camera_nodelet.dir/src/cv_camera_nodelet.cpp.o] Error 1
CMakeFiles/Makefile2:6479: recipe for target 'sensors/cv_camera/CMakeFiles/cv_camera_nodelet.dir/all' failed
make[1]: *** [sensors/cv_camera/CMakeFiles/cv_camera_nodelet.dir/all] Error 2
Makefile:140: recipe for target 'all' failed
make: *** [all] Error 2
Invoking "make -j12 -l12" failed`

**Comment by NeilNie** [comment]
Can you please provide your ROS distro and ubuntu distro? Thanks!

**Comment by Hossam-Elbahrawy** [comment]
> Can you please provide your ROS distro and ubuntu distro? Thanks!

I am using Ubuntu 18.04.2 LTS and ROS melodic.

**Comment by NeilNie** [comment]
I had some issues with `cv_camera`. I created a new package called `camera`. I haven't tested it yet, but it should work just like cv_camera. Instead of using roscpp, everything is in rospy. For more information, please refer to commit: 7a4fdfb84b244b6758243c1cf353469bc3ae6ec6 . I will test as soon as I get a chance. Will update if I find any issues.

**Comment by NeilNie** [comment]
Closing for now.
