### ISSUE TITLE
Question in the mapping package ?

### ISSUE THREAD

**Issue by JackRen88** [sigmaai/self-driving-golf-cart#16]
Hello.
I found that there is some launch files being used for mapping which use the rtabmap_ros package,what is the function of build_map node in the mapping package?

**Comment by NeilNie** [comment]
Hello @JackRen88 

You raised a good question. The `build_map` node is my attempt to create local maps for the autonomous vehicle without using the rtabmap package. 

The goal is to use 2d image semantic segmentation to segment the raw point cloud data from the stereoscopic camera. And then, with the segmented point cloud create a local map around the vehicle. However, my attempt was very unsuccessful. I haven't had time to fix this issue. The rtabmap system works relatively well. 

As a general note, this project lacks good documentation as I am the only person trying to write docs for it. I will try to make sure that everything is well documented.
