### ISSUE TITLE
Can the mapping method used in this library be built in the Carla simulator?

### ISSUE THREAD

**Issue by JackRen88** [sigmaai/self-driving-golf-cart#19]
Hello.
I am very interested in your project.
I found that the actual auto-driving function was implemented in the project using traditional auto-driving methods (such as sensing, planning, and control), but it was not implemented in the Carla simulator. Is the method you use available in the Carla simulator? For example, can you map with rtabamp in the Carla simulator, and if so, what should I do?

**Comment by NeilNie** [comment]
Hello @JackRen88 

Thank you for checking out the project. You are correct to say that this project largely uses traditional self-driving methods. Unfortunately, I haven't had a chance to implement that into CARLO. With that being said, it's **totally possible** to map with rtabmap in CARLA. 

I am not very familiar with CARLA. I imagine the best way to do this would be first run CARLA and CARLA's ROS bridge. This will allow CARLA to publish all of the simulated sensor outputs. Then, you would need to subscribe to the depth map, rgb image and such. (You need to map the CARLA published topics to the topics of this project). This project (ROS bridge) is very important and helpful: https://github.com/carla-simulator/ros-bridge

You can find the doc on all of CARLA's sensors here: https://carla.readthedocs.io/en/latest/bp_library/#sensor

Good luck! I hope one day I will be able to integrate this project to CARLA. With that being said, feel free to fork and make headway on this. And maybe one day submit a merge requestion. 

Best regards,

Neil

**Comment by JackRen88** [comment]
Thank you for your patience.
I don't kown  how to use your  mapping package,can you guide me? Such as which files should I start first?

**Comment by NeilNie** [comment]
First, I would recommend you using the `rtabmap_mapping.launch` file to create a map of the environment. Second, to use the map for navigation, you need to run two launch files: `rtabmap.launch` `rtabmap_navigation.launch`. I will update the documentations. Furthermore, I have created a project related to the CARLA simulation. I have also created a new branch call `simulation`. I will close this issue for now. Please don't hesitate to post a comment.
