### ISSUE TITLE
Hardcoded path

### ISSUE THREAD

**Issue by overlapjho** [sigmaai/self-driving-golf-cart#6]
Hi, some of the Makefile paths are hardcoded causes installation problem on other machine.

`~/Desktop/self-driving-golf-cart/ros/Makefile`

```
# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/neil/Workspace/self-driving-golf-cart/ros/src

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/neil/Workspace/self-driving-golf-cart/ros/src
```

**Comment by NeilNie** [comment]
Hi @overlapjho,

The hardcoded paths you pointed out are a part of the ros build and devel directory. These directories are automatically generated on the local machine. They shouldn't be apart of Github. I removed these directories and added them to git ignore. see commit: bf797f6faff153eeadbe8eec77eefcbf89068ba4 and 1ec8e33acb9fab6d3ee10700422a6f27d557484f

Closing this issue. 

Thanks,

Neil
