### ISSUE TITLE
Could not find a package configuration file provided by   "derived_object_msgs" 

### ISSUE THREAD

**Issue by nishanthjois** [sigmaai/self-driving-golf-cart#8]
Am getting error on running catkin_make
CMake Error at /opt/ros/melodic/share/catkin/cmake/catkinConfig.cmake:83 (find_package):
  Could not find a package configuration file provided by
  "derived_object_msgs" with any of the following names:

    derived_object_msgsConfig.cmake
    derived_object_msgs-config.cmake

  Add the installation prefix of "derived_object_msgs" to CMAKE_PREFIX_PATH
  or set "derived_object_msgs_DIR" to a directory containing one of the above
  files.  If "derived_object_msgs" provides a separate development package or
  SDK, be sure it has been installed.
Call Stack (most recent call first):
  simulation/CMakeLists.txt:5 (find_package)

Ubuntu: 18.04
Ros: Melodic

Tried to do below step:
sudo apt-get install ros-melodic-derived-object-sensor-msgs

It says:
E: Unable to locate package ros-melodic-derived-object-sensor-msgs

Any idea how to fix?

**Comment by NeilNie** [comment]
Hi, you need to install `astuff_sensor_msgs`. Try this: 

`sudo apt-get install ros-melodic-astuff-sensor-msgs`

**Comment by nishanthjois** [comment]
Thanks a lot, this worked.
